"""
seed_all.py — Seed direto no banco (sem HTTP).
Chamado automaticamente no startup se o banco estiver vazio.
"""
from database import Institution


ESCOLAS = [
    ("Colegio Estadual Helio Melo", "AC", "Rio Branco"),
    ("Centro de Ensino Medio Amalia Amorim", "AC", "Rio Branco"),
    ("Colegio Estadual Governador Lamenha Filho", "AL", "Maceio"),
    ("Centro Educacional Marista de Maceio", "AL", "Maceio"),
    ("Colegio Arquidiocesano Nossa Senhora Auxiliadora", "AL", "Maceio"),
    ("Centro de Ensino Medio Augusto Antunes", "AP", "Macapa"),
    ("Colegio Estadual Marco Zero do Equador", "AP", "Macapa"),
    ("Colegio Militar de Manaus", "AM", "Manaus"),
    ("Centro de Ensino Dom Bosco", "AM", "Manaus"),
    ("Colegio Nossa Senhora Auxiliadora", "AM", "Manaus"),
    ("Colegio Salesiano Dom Bosco Manaus", "AM", "Manaus"),
    ("Colegio Militar de Salvador", "BA", "Salvador"),
    ("Colegio Central (Instituto Central de Educacao Isaias Alves)", "BA", "Salvador"),
    ("Colegio Estadual Governador Lomanto Junior", "BA", "Salvador"),
    ("Colegio Nossa Senhora da Luz", "BA", "Salvador"),
    ("Colegio Marista Salvador", "BA", "Salvador"),
    ("Colegio Salesiano Nossa Senhora Auxiliadora Salvador", "BA", "Salvador"),
    ("Colegio Sao Jose de Salvador", "BA", "Salvador"),
    ("Colegio Nossa Senhora da Conceicao (Feira de Santana)", "BA", "Feira de Santana"),
    ("Colegio Estadual Agora Balthazar", "BA", "Vitoria da Conquista"),
    ("Colegio Nossa Senhora de Lourdes Palmares", "PE", "Palmares"),
    ("Colegio Militar de Fortaleza", "CE", "Fortaleza"),
    ("Liceu do Ceara", "CE", "Fortaleza"),
    ("Colegio Farias Brito", "CE", "Fortaleza"),
    ("Colegio Sao Joao Fortaleza", "CE", "Fortaleza"),
    ("Colegio Santo Inacio Fortaleza", "CE", "Fortaleza"),
    ("Colegio Nossa Senhora das Gracas Fortaleza", "CE", "Fortaleza"),
    ("Colegio Ari de Sa Cavalcante", "CE", "Fortaleza"),
    ("Centro de Ensino Unificado de Fortaleza (CEFOR)", "CE", "Fortaleza"),
    ("Colegio Lourenco Filho", "CE", "Fortaleza"),
    ("Escola Estadual de Educacao Profissional EEFM Jose Albano", "CE", "Sobral"),
    ("Colegio Militar de Brasilia", "DF", "Brasilia"),
    ("Centro Educacional La Salle Brasilia", "DF", "Brasilia"),
    ("Colegio Nossa Senhora de Fatima Brasilia", "DF", "Brasilia"),
    ("Colegio Marista Brasilia", "DF", "Brasilia"),
    ("Centro de Ensino Medio Elefante Branco", "DF", "Brasilia"),
    ("Centro de Ensino Medio Ave Branca", "DF", "Brasilia"),
    ("Colegio Estadual Goncalves Dias", "ES", "Vitoria"),
    ("Colegio Nossa Senhora Auxiliadora Vitoria", "ES", "Vitoria"),
    ("Colegio Marista Sao Joao Vitoria", "ES", "Vitoria"),
    ("Colegio Salesiano Cariacica", "ES", "Cariacica"),
    ("Colegio Estadual Lyceu de Goiania", "GO", "Goiania"),
    ("Colegio Marista Pio XII Goiania", "GO", "Goiania"),
    ("Colegio Nossa Senhora de Fatima Goiania", "GO", "Goiania"),
    ("Colegio Santa Clara Goiania", "GO", "Goiania"),
    ("Colegio Militar de Goias", "GO", "Goiania"),
    ("Colegio Salesiano Dom Bosco Goiania", "GO", "Goiania"),
    ("Colegio Militar de Sao Luis", "MA", "Sao Luis"),
    ("Colegio Liceu Maranhanense", "MA", "Sao Luis"),
    ("Colegio Nossa Senhora das Gracas Sao Luis", "MA", "Sao Luis"),
    ("Colegio Sao Luis Sao Luis", "MA", "Sao Luis"),
    ("Colegio Salesiano Nossa Senhora Auxiliadora Sao Luis", "MA", "Sao Luis"),
    ("Escola Estadual Liceu Cuiabano", "MT", "Cuiaba"),
    ("Colegio Salesiano Sao Domingos Savio Cuiaba", "MT", "Cuiaba"),
    ("Colegio Marista Cuiaba", "MT", "Cuiaba"),
    ("Colegio Estadual Maria Constanca Barros Machado", "MS", "Campo Grande"),
    ("Colegio Dom Bosco Campo Grande", "MS", "Campo Grande"),
    ("Colegio Marista Nossa Senhora da Abadia", "MS", "Campo Grande"),
    ("Escola Estadual Joaquim Murtinho", "MS", "Campo Grande"),
    ("Colegio Militar de Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Estadual Central de Minas Gerais", "MG", "Belo Horizonte"),
    ("Colegio Santo Agostinho Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Dom Bosco Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Marista Nossa Senhora das Gracas BH", "MG", "Belo Horizonte"),
    ("Colegio Loyola Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Sao Joao BH", "MG", "Belo Horizonte"),
    ("Colegio Anchieta Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Salesiano Dom Bosco Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Santa Maria Belo Horizonte", "MG", "Belo Horizonte"),
    ("Colegio Estadual Henrique Diniz", "MG", "Uberlandia"),
    ("Escola Estadual Bueno Brandao", "MG", "Juiz de Fora"),
    ("Colegio Santo Antonio Juiz de Fora", "MG", "Juiz de Fora"),
    ("Colegio Militar de Belem", "PA", "Belem"),
    ("Escola Estadual Paes de Carvalho", "PA", "Belem"),
    ("Colegio Nossa Senhora de Nazare Belem", "PA", "Belem"),
    ("Colegio Salesiano Nossa Senhora Auxiliadora Belem", "PA", "Belem"),
    ("Colegio Marista Assuncao Belem", "PA", "Belem"),
    ("Colegio Estadual da Paraiba", "PB", "Joao Pessoa"),
    ("Colegio Pio X Joao Pessoa", "PB", "Joao Pessoa"),
    ("Escola Estadual Alcides Bezerra", "PB", "Joao Pessoa"),
    ("Colegio Nossa Senhora das Neves Joao Pessoa", "PB", "Joao Pessoa"),
    ("Escola Estadual de Comercio Epitacio Pessoa", "PB", "Joao Pessoa"),
    ("Colegio Estadual Epitacio Pessoa Campina Grande", "PB", "Campina Grande"),
    ("Colegio Estadual do Parana", "PR", "Curitiba"),
    ("Colegio Militar de Curitiba", "PR", "Curitiba"),
    ("Colegio Notre Dame Curitiba", "PR", "Curitiba"),
    ("Colegio Santa Maria Curitiba", "PR", "Curitiba"),
    ("Colegio Marista Curitiba", "PR", "Curitiba"),
    ("Colegio Salesiano Santa Rosa Curitiba", "PR", "Curitiba"),
    ("Colegio Santo Inacio Curitiba", "PR", "Curitiba"),
    ("Colegio Positivo Curitiba", "PR", "Curitiba"),
    ("Colegio Bom Jesus Curitiba", "PR", "Curitiba"),
    ("Colegio Sao Jose Curitiba", "PR", "Curitiba"),
    ("Instituto de Educacao do Parana Professor Erasmo Pilotto", "PR", "Curitiba"),
    ("Colegio Estadual Professor Brasilio Itibere", "PR", "Curitiba"),
    ("Colegio Militar do Recife", "PE", "Recife"),
    ("Colegio Nobre Sao Jose", "PE", "Recife"),
    ("Colegio Nossa Senhora do Carmo Recife", "PE", "Recife"),
    ("Colegio Santa Doroteia Recife", "PE", "Recife"),
    ("Colegio Salesiano Recife", "PE", "Recife"),
    ("Colegio Santa Maria Recife", "PE", "Recife"),
    ("Colegio Santa Cruz Recife", "PE", "Recife"),
    ("Colegio Marista Recife", "PE", "Recife"),
    ("Escola Estadual Professor Amorim", "PE", "Recife"),
    ("Colegio Anglo Recife", "PE", "Recife"),
    ("Colegio Estadual de Pernambuco", "PE", "Recife"),
    ("Colegio Nossa Senhora de Lourdes Recife", "PE", "Recife"),
    ("Colegio Boa Viagem Recife", "PE", "Recife"),
    ("Escola de Referencia em Ensino Medio Apolonio Sales", "PE", "Caruaru"),
    ("Colegio Estadual Zacarias de Goes", "PI", "Teresina"),
    ("Colegio Sagrado Coracao de Jesus Teresina", "PI", "Teresina"),
    ("Colegio Sao Francisco de Sales Teresina", "PI", "Teresina"),
    ("Escola Estadual Antonino Freire", "PI", "Teresina"),
    ("Colegio Pedro II (Sede)", "RJ", "Rio de Janeiro"),
    ("Colegio Militar do Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Santo Inacio Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Sao Bento Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Nossa Senhora de Sion Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Andrews Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Estadual Amaro Cavalcanti", "RJ", "Rio de Janeiro"),
    ("Colegio Estadual Ferreira Viana", "RJ", "Rio de Janeiro"),
    ("Instituto de Educacao do Rio de Janeiro (IERJ)", "RJ", "Rio de Janeiro"),
    ("Colegio Nossa Senhora Auxiliadora Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Salesiano Santa Rosa Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio La Salle Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio Santa Teresa Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Colegio de Aplicacao UERJ", "RJ", "Rio de Janeiro"),
    ("Colegio Estadual Candido Mendes Niteroi", "RJ", "Niteroi"),
    ("Escola Estadual Joao Pessoa Volta Redonda", "RJ", "Volta Redonda"),
    ("Colegio Estadual Augusto Severo", "RN", "Natal"),
    ("Ateneu Norte-Rio-Grandense", "RN", "Natal"),
    ("Colegio Nossa Senhora das Neves Natal", "RN", "Natal"),
    ("Colegio Salesiano Natal", "RN", "Natal"),
    ("Colegio Marista Natal", "RN", "Natal"),
    ("Colegio Militar de Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Estadual Julio de Castilhos", "RS", "Porto Alegre"),
    ("Instituto Estadual de Educacao Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Anchieta Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Farroupilha Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Sao Luis Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Notre Dame Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Israelita Brasileiro Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio La Salle Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Salesiano Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Champagnat Porto Alegre", "RS", "Porto Alegre"),
    ("Colegio Santos Anjos Porto Alegre", "RS", "Porto Alegre"),
    ("Escola Estadual de Ensino Medio Pinheiro Machado", "RS", "Porto Alegre"),
    ("Colegio Estadual Sao Leopoldo", "RS", "Sao Leopoldo"),
    ("Colegio Sao Luis Ijui", "RS", "Ijui"),
    ("Escola Estadual Carmela Dutra", "RO", "Porto Velho"),
    ("Colegio Nossa Senhora das Gracas Porto Velho", "RO", "Porto Velho"),
    ("Escola Estadual Monteiro Lobato Boa Vista", "RR", "Boa Vista"),
    ("Colegio Estadual Aniceto Mossimann", "SC", "Florianopolis"),
    ("Colegio Catarinense Florianopolis", "SC", "Florianopolis"),
    ("Colegio Coracao de Jesus Florianopolis", "SC", "Florianopolis"),
    ("Colegio Salesiano Sao Jose Florianopolis", "SC", "Florianopolis"),
    ("Instituto Estadual de Educacao Florianopolis", "SC", "Florianopolis"),
    ("Colegio Medianeira Florianopolis", "SC", "Florianopolis"),
    ("Escola Estadual Basica Simao Jose Hess", "SC", "Florianopolis"),
    ("Escola Estadual Adolfo Konder", "SC", "Blumenau"),
    ("Colegio Sagrada Familia Blumenau", "SC", "Blumenau"),
    ("Colegio Sao Luis Joinville", "SC", "Joinville"),
    ("Colegio Estadual Atheneu Sergipense", "SE", "Aracaju"),
    ("Colegio Nossa Senhora de Lourdes Aracaju", "SE", "Aracaju"),
    ("Colegio Salesiano Nossa Senhora Auxiliadora Aracaju", "SE", "Aracaju"),
    ("Colegio Militar de Sao Paulo", "SP", "Sao Paulo"),
    ("Escola Estadual Fernao Dias Paes", "SP", "Sao Paulo"),
    ("Escola Estadual Caetano de Campos", "SP", "Sao Paulo"),
    ("Colegio Sao Bento Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Nossa Senhora das Gracas Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Marista Arquidiocesano Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Salesiano Dom Bosco Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Santo Inacio Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Bandeirantes Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Anglo Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Etapa Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Objetivo Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Mackenzie Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Albert Einstein Sao Paulo", "SP", "Sao Paulo"),
    ("Escola Estadual Presidente Vargas Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Sao Joao Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio La Salle Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Notre Dame Sao Paulo", "SP", "Sao Paulo"),
    ("Escola Estadual Joao Kopke", "SP", "Sao Paulo"),
    ("Escola Estadual Rodrigues Alves", "SP", "Sao Paulo"),
    ("Colegio Sao Luis Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Estadual Oswaldo Cruz Sao Paulo", "SP", "Sao Paulo"),
    ("Colegio Anglo Campinas", "SP", "Campinas"),
    ("Colegio Salesiano Dom Bosco Campinas", "SP", "Campinas"),
    ("Colegio Marista Campinas", "SP", "Campinas"),
    ("Escola Estadual Carlos Gomes Campinas", "SP", "Campinas"),
    ("Colegio Santa Marcelina Santos", "SP", "Santos"),
    ("Colegio Macedo Soares Santos", "SP", "Santos"),
    ("Colegio Sao Francisco de Assis Ribeirao Preto", "SP", "Ribeirao Preto"),
    ("Escola Estadual Otoniel Mota Ribeirao Preto", "SP", "Ribeirao Preto"),
    ("Colegio Dom Bosco Sao Jose dos Campos", "SP", "Sao Jose dos Campos"),
    ("Colegio Estadual Joaquim Teotonio Segurado", "TO", "Palmas"),
    ("Colegio Estadual Modelo Palmas", "TO", "Palmas"),
]

CIDADES = [
    ("Rio Branco", "AC", "Rio Branco"),
    ("Maceio", "AL", "Maceio"),
    ("Macapa", "AP", "Macapa"),
    ("Manaus", "AM", "Manaus"),
    ("Salvador", "BA", "Salvador"),
    ("Fortaleza", "CE", "Fortaleza"),
    ("Brasilia", "DF", "Brasilia"),
    ("Vitoria", "ES", "Vitoria"),
    ("Goiania", "GO", "Goiania"),
    ("Sao Luis", "MA", "Sao Luis"),
    ("Cuiaba", "MT", "Cuiaba"),
    ("Campo Grande", "MS", "Campo Grande"),
    ("Belo Horizonte", "MG", "Belo Horizonte"),
    ("Belem", "PA", "Belem"),
    ("Joao Pessoa", "PB", "Joao Pessoa"),
    ("Curitiba", "PR", "Curitiba"),
    ("Recife", "PE", "Recife"),
    ("Teresina", "PI", "Teresina"),
    ("Rio de Janeiro", "RJ", "Rio de Janeiro"),
    ("Natal", "RN", "Natal"),
    ("Porto Alegre", "RS", "Porto Alegre"),
    ("Porto Velho", "RO", "Porto Velho"),
    ("Boa Vista", "RR", "Boa Vista"),
    ("Florianopolis", "SC", "Florianopolis"),
    ("Aracaju", "SE", "Aracaju"),
    ("Sao Paulo", "SP", "Sao Paulo"),
    ("Palmas", "TO", "Palmas"),
    ("Campinas", "SP", "Campinas"),
    ("Santos", "SP", "Santos"),
    ("Sao Bernardo do Campo", "SP", "Sao Bernardo do Campo"),
    ("Santo Andre", "SP", "Santo Andre"),
    ("Osasco", "SP", "Osasco"),
    ("Ribeirao Preto", "SP", "Ribeirao Preto"),
    ("Sorocaba", "SP", "Sorocaba"),
    ("Sao Jose dos Campos", "SP", "Sao Jose dos Campos"),
    ("Mogi das Cruzes", "SP", "Mogi das Cruzes"),
    ("Sao Jose do Rio Preto", "SP", "Sao Jose do Rio Preto"),
    ("Bauru", "SP", "Bauru"),
    ("Piracicaba", "SP", "Piracicaba"),
    ("Limeira", "SP", "Limeira"),
    ("Guarulhos", "SP", "Guarulhos"),
    ("Niteroi", "RJ", "Niteroi"),
    ("Nova Iguacu", "RJ", "Nova Iguacu"),
    ("Duque de Caxias", "RJ", "Duque de Caxias"),
    ("Volta Redonda", "RJ", "Volta Redonda"),
    ("Petropolis", "RJ", "Petropolis"),
    ("Macae", "RJ", "Macae"),
    ("Uberlandia", "MG", "Uberlandia"),
    ("Contagem", "MG", "Contagem"),
    ("Juiz de Fora", "MG", "Juiz de Fora"),
    ("Betim", "MG", "Betim"),
    ("Montes Claros", "MG", "Montes Claros"),
    ("Uberaba", "MG", "Uberaba"),
    ("Governador Valadares", "MG", "Governador Valadares"),
    ("Ipatinga", "MG", "Ipatinga"),
    ("Ouro Preto", "MG", "Ouro Preto"),
    ("Diamantina", "MG", "Diamantina"),
    ("Canoas", "RS", "Canoas"),
    ("Pelotas", "RS", "Pelotas"),
    ("Caxias do Sul", "RS", "Caxias do Sul"),
    ("Santa Maria", "RS", "Santa Maria"),
    ("Novo Hamburgo", "RS", "Novo Hamburgo"),
    ("Sao Leopoldo", "RS", "Sao Leopoldo"),
    ("Passo Fundo", "RS", "Passo Fundo"),
    ("Londrina", "PR", "Londrina"),
    ("Maringa", "PR", "Maringa"),
    ("Ponta Grossa", "PR", "Ponta Grossa"),
    ("Cascavel", "PR", "Cascavel"),
    ("Foz do Iguacu", "PR", "Foz do Iguacu"),
    ("Joinville", "SC", "Joinville"),
    ("Blumenau", "SC", "Blumenau"),
    ("Chapeco", "SC", "Chapeco"),
    ("Itajai", "SC", "Itajai"),
    ("Criciuma", "SC", "Criciuma"),
    ("Feira de Santana", "BA", "Feira de Santana"),
    ("Vitoria da Conquista", "BA", "Vitoria da Conquista"),
    ("Camacari", "BA", "Camacari"),
    ("Ilheus", "BA", "Ilheus"),
    ("Itabuna", "BA", "Itabuna"),
    ("Caruaru", "PE", "Caruaru"),
    ("Olinda", "PE", "Olinda"),
    ("Petrolina", "PE", "Petrolina"),
    ("Paulista", "PE", "Paulista"),
    ("Palmares", "PE", "Palmares"),
    ("Caucaia", "CE", "Caucaia"),
    ("Juazeiro do Norte", "CE", "Juazeiro do Norte"),
    ("Sobral", "CE", "Sobral"),
    ("Crato", "CE", "Crato"),
    ("Aparecida de Goiania", "GO", "Aparecida de Goiania"),
    ("Anapolis", "GO", "Anapolis"),
    ("Rio Verde", "GO", "Rio Verde"),
    ("Ananindeua", "PA", "Ananindeua"),
    ("Santarem", "PA", "Santarem"),
    ("Maraba", "PA", "Maraba"),
    ("Imperatriz", "MA", "Imperatriz"),
    ("Timon", "MA", "Timon"),
    ("Caxias", "MA", "Caxias"),
    ("Parintins", "AM", "Parintins"),
    ("Itacoatiara", "AM", "Itacoatiara"),
    ("Mossoro", "RN", "Mossoro"),
    ("Parnamirim", "RN", "Parnamirim"),
    ("Arapiraca", "AL", "Arapiraca"),
    ("Palmeira dos Indios", "AL", "Palmeira dos Indios"),
    ("Nossa Senhora do Socorro", "SE", "Nossa Senhora do Socorro"),
    ("Lagarto", "SE", "Lagarto"),
    ("Parnaiba", "PI", "Parnaiba"),
    ("Picos", "PI", "Picos"),
    ("Campina Grande", "PB", "Campina Grande"),
    ("Santa Rita", "PB", "Santa Rita"),
    ("Rondonopolis", "MT", "Rondonopolis"),
    ("Sinop", "MT", "Sinop"),
    ("Varzea Grande", "MT", "Varzea Grande"),
    ("Dourados", "MS", "Dourados"),
    ("Tres Lagoas", "MS", "Tres Lagoas"),
    ("Corumba", "MS", "Corumba"),
    ("Vila Velha", "ES", "Vila Velha"),
    ("Serra", "ES", "Serra"),
    ("Cariacica", "ES", "Cariacica"),
    ("Cachoeiro de Itapemirim", "ES", "Cachoeiro de Itapemirim"),
    ("Araguaina", "TO", "Araguaina"),
    ("Ji-Parana", "RO", "Ji-Parana"),
    ("Rorainopolis", "RR", "Rorainopolis"),
    ("Santana", "AP", "Santana"),
    ("Cruzeiro do Sul", "AC", "Cruzeiro do Sul"),
]

EMPRESAS = [
    ("Petrobras", "RJ", "Rio de Janeiro"),
    ("Shell Brasil", "RJ", "Rio de Janeiro"),
    ("TotalEnergies Brasil", "RJ", "Rio de Janeiro"),
    ("Raizen", "SP", "Sao Paulo"),
    ("Vibra Energia (BR Distribuidora)", "RJ", "Rio de Janeiro"),
    ("Eletrobras", "RJ", "Rio de Janeiro"),
    ("Cemig", "MG", "Belo Horizonte"),
    ("Copel", "PR", "Curitiba"),
    ("CPFL Energia", "SP", "Campinas"),
    ("Engie Brasil", "SC", "Florianopolis"),
    ("Equatorial Energia", "MA", "Sao Luis"),
    ("Neoenergia", "BA", "Salvador"),
    ("Enel Brasil", "SP", "Sao Paulo"),
    ("Vale", "RJ", "Rio de Janeiro"),
    ("Gerdau", "RS", "Porto Alegre"),
    ("CSN (Companhia Siderurgica Nacional)", "RJ", "Rio de Janeiro"),
    ("Usiminas", "MG", "Belo Horizonte"),
    ("ArcelorMittal Brasil", "MG", "Belo Horizonte"),
    ("Samarco Mineracao", "ES", "Vitoria"),
    ("Anglo American Brasil", "MG", "Belo Horizonte"),
    ("Kinross Brasil Mineracao", "MG", "Belo Horizonte"),
    ("Banco do Brasil", "DF", "Brasilia"),
    ("Bradesco", "SP", "Osasco"),
    ("Itau Unibanco", "SP", "Sao Paulo"),
    ("Caixa Economica Federal", "DF", "Brasilia"),
    ("Santander Brasil", "SP", "Sao Paulo"),
    ("BTG Pactual", "SP", "Sao Paulo"),
    ("XP Investimentos", "SP", "Sao Paulo"),
    ("Nubank", "SP", "Sao Paulo"),
    ("Inter (Banco Inter)", "MG", "Belo Horizonte"),
    ("Sicredi", "RS", "Porto Alegre"),
    ("Sicoob", "DF", "Brasilia"),
    ("Banrisul", "RS", "Porto Alegre"),
    ("Banco do Nordeste (BNB)", "CE", "Fortaleza"),
    ("BNDES", "RJ", "Rio de Janeiro"),
    ("Claro Brasil", "SP", "Sao Paulo"),
    ("Vivo (Telefonica Brasil)", "SP", "Sao Paulo"),
    ("TIM Brasil", "RJ", "Rio de Janeiro"),
    ("Oi", "RJ", "Rio de Janeiro"),
    ("Embratel", "RJ", "Rio de Janeiro"),
    ("Algar Telecom", "MG", "Uberlandia"),
    ("Mercado Livre Brasil", "SP", "Sao Paulo"),
    ("Americanas", "RJ", "Rio de Janeiro"),
    ("Magazineluiza (Magalu)", "SP", "Franca"),
    ("Grupo Pao de Acucar (GPA)", "SP", "Sao Paulo"),
    ("Carrefour Brasil", "SP", "Sao Paulo"),
    ("Atacadao", "SP", "Sao Paulo"),
    ("Casas Bahia (Via Varejo)", "SP", "Sao Paulo"),
    ("Riachuelo", "SP", "Sao Paulo"),
    ("Renner", "RS", "Porto Alegre"),
    ("C&A Brasil", "SP", "Sao Paulo"),
    ("Hering", "SC", "Blumenau"),
    ("Arezzo", "MG", "Belo Horizonte"),
    ("Grupo Soma", "RJ", "Rio de Janeiro"),
    ("Totvs", "SP", "Sao Paulo"),
    ("Localiza", "MG", "Belo Horizonte"),
    ("Movida", "SP", "Sao Paulo"),
    ("Unidas", "MG", "Belo Horizonte"),
    ("JBS", "SP", "Sao Paulo"),
    ("BRF (Brasil Foods)", "SP", "Sao Paulo"),
    ("Marfrig", "SP", "Sao Paulo"),
    ("Minerva Foods", "SP", "Sao Paulo"),
    ("Ambev", "SP", "Sao Paulo"),
    ("Heineken Brasil", "SP", "Sao Paulo"),
    ("Coca-Cola Brasil", "SP", "Rio de Janeiro"),
    ("Nestle Brasil", "SP", "Sao Paulo"),
    ("Unilever Brasil", "SP", "Sao Paulo"),
    ("Sadia", "SC", "Concordia"),
    ("Perdigao", "SC", "Videira"),
    ("Vigor Alimentos", "SP", "Sao Paulo"),
    ("M. Dias Branco", "CE", "Eusebio"),
    ("Embrapa", "DF", "Brasilia"),
    ("Copersucar", "SP", "Sao Paulo"),
    ("SLC Agricola", "RS", "Porto Alegre"),
    ("Amaggi (Andre Maggi)", "MT", "Cuiaba"),
    ("Louis Dreyfus Brasil", "SP", "Sao Paulo"),
    ("Cargill Brasil", "SP", "Sao Paulo"),
    ("ADM do Brasil", "SP", "Sao Paulo"),
    ("Bunge Brasil", "SP", "Sao Paulo"),
    ("Embraer", "SP", "Sao Jose dos Campos"),
    ("Fiat Chrysler Brasil (Stellantis)", "MG", "Betim"),
    ("Volkswagen do Brasil", "SP", "Sao Paulo"),
    ("General Motors Brasil", "SP", "Sao Paulo"),
    ("Ford Brasil", "BA", "Camacari"),
    ("Toyota do Brasil", "SP", "Indaiatuba"),
    ("Honda Brasil", "SP", "Sumare"),
    ("Renault do Brasil", "PR", "Curitiba"),
    ("Volvo do Brasil", "PR", "Curitiba"),
    ("WEG Industrias", "SC", "Jaragua do Sul"),
    ("Whirlpool (Brastemp/Consul)", "SP", "Sao Paulo"),
    ("Electrolux do Brasil", "SC", "Sao Carlos"),
    ("3M Brasil", "SP", "Sumare"),
    ("Bosch Brasil", "SP", "Campinas"),
    ("Embraco", "SC", "Joinville"),
    ("Intelbras", "SC", "Sao Jose"),
    ("Randon Implementos", "RS", "Caxias do Sul"),
    ("Marcopolo", "RS", "Caxias do Sul"),
    ("MRV Engenharia", "MG", "Belo Horizonte"),
    ("Cyrela", "SP", "Sao Paulo"),
    ("Gafisa", "SP", "Sao Paulo"),
    ("Tenda", "SP", "Sao Paulo"),
    ("Direcional Engenharia", "MG", "Belo Horizonte"),
    ("Even Construtora", "SP", "Sao Paulo"),
    ("EZTec", "SP", "Sao Paulo"),
    ("Odebrecht (Novonor)", "BA", "Salvador"),
    ("Andrade Gutierrez", "MG", "Belo Horizonte"),
    ("OAS", "BA", "Salvador"),
    ("WTorre", "SP", "Sao Paulo"),
    ("Rede D'Or Sao Luiz", "RJ", "Rio de Janeiro"),
    ("Hapvida", "CE", "Fortaleza"),
    ("NotreDame Intermedica", "SP", "Sao Paulo"),
    ("Unimed Brasil", "SP", "Sao Paulo"),
    ("Dasa (Diagnosticos da America)", "SP", "Barueri"),
    ("Fleury Medicina e Saude", "SP", "Sao Paulo"),
    ("Hermes Pardini", "MG", "Belo Horizonte"),
    ("Hypera Pharma", "SP", "Sao Paulo"),
    ("Correios (ECT)", "DF", "Brasilia"),
    ("Latam Airlines Brasil", "SP", "Sao Paulo"),
    ("Gol Linhas Aereas", "SP", "Sao Paulo"),
    ("Azul Linhas Aereas", "SP", "Campinas"),
    ("JSL Logistica", "SP", "Sao Paulo"),
    ("CI&T", "SP", "Campinas"),
    ("Stefanini", "SP", "Sao Paulo"),
    ("Accenture Brasil", "SP", "Sao Paulo"),
    ("IBM Brasil", "SP", "Sao Paulo"),
    ("SAP Brasil", "SP", "Sao Paulo"),
    ("Oracle Brasil", "SP", "Sao Paulo"),
    ("Wipro Brasil", "SP", "Sao Paulo"),
    ("Capgemini Brasil", "SP", "Sao Paulo"),
    ("Senior Sistemas", "SC", "Blumenau"),
    ("VTEX", "RJ", "Rio de Janeiro"),
    ("Resultados Digitais (RD Station)", "SC", "Florianopolis"),
    ("Hotmart", "MG", "Belo Horizonte"),
    ("iFood", "SP", "Osasco"),
    ("99 (DiDi Brasil)", "SP", "Sao Paulo"),
    ("Rappi Brasil", "SP", "Sao Paulo"),
    ("Creditas", "SP", "Sao Paulo"),
    ("Suzano Papel e Celulose", "SP", "Sao Paulo"),
    ("Klabin", "SP", "Sao Paulo"),
    ("Eldorado Brasil Celulose", "MS", "Tres Lagoas"),
    ("Porto Seguro", "SP", "Sao Paulo"),
    ("SulAmerica Seguros", "SP", "Sao Paulo"),
    ("Tokio Marine Brasil", "SP", "Sao Paulo"),
    ("Mapfre Brasil", "SP", "Sao Paulo"),
    ("Vivara Joias", "SP", "Sao Paulo"),
    ("Grupo Boticario", "PR", "Curitiba"),
    ("Natura Cosmeticos", "SP", "Sao Paulo"),
    ("Avon Brasil", "SP", "Sao Paulo"),
    ("L'Oreal Brasil", "SP", "Sao Paulo"),
    ("Unicharm Brasil", "SP", "Sao Paulo"),
    ("Ypê Quimica", "SP", "Amparo"),
    ("Ultrapar (Ipiranga)", "SP", "Sao Paulo"),
    ("Fleischmann Royal Brasile", "SP", "Sao Paulo"),
]

UNIVERSIDADES = [
    ("Universidade de Sao Paulo (USP)", "SP", "Sao Paulo"),
    ("Universidade Estadual de Campinas (UNICAMP)", "SP", "Campinas"),
    ("Universidade Estadual Paulista (UNESP)", "SP", "Sao Paulo"),
    ("Universidade Virtual do Estado de Sao Paulo (UNIVESP)", "SP", "Sao Paulo"),
    ("Universidade do Estado do Rio de Janeiro (UERJ)", "RJ", "Rio de Janeiro"),
    ("Universidade Estadual do Norte Fluminense (UENF)", "RJ", "Campos dos Goytacazes"),
    ("Universidade do Grande Rio (UNIGRANRIO)", "RJ", "Duque de Caxias"),
    ("Universidade do Estado de Minas Gerais (UEMG)", "MG", "Belo Horizonte"),
    ("Universidade Estadual de Montes Claros (UNIMONTES)", "MG", "Montes Claros"),
    ("Universidade Estadual de Feira de Santana (UEFS)", "BA", "Feira de Santana"),
    ("Universidade Estadual de Santa Cruz (UESC)", "BA", "Ilheus"),
    ("Universidade Estadual do Sudoeste da Bahia (UESB)", "BA", "Vitoria da Conquista"),
    ("Universidade do Estado da Bahia (UNEB)", "BA", "Salvador"),
    ("Universidade Estadual do Ceara (UECE)", "CE", "Fortaleza"),
    ("Universidade Regional do Cariri (URCA)", "CE", "Crato"),
    ("Universidade Estadual Vale do Acara (UVA)", "CE", "Sobral"),
    ("Universidade de Pernambuco (UPE)", "PE", "Recife"),
    ("Universidade Estadual de Londrina (UEL)", "PR", "Londrina"),
    ("Universidade Estadual de Maringa (UEM)", "PR", "Maringa"),
    ("Universidade Estadual de Ponta Grossa (UEPG)", "PR", "Ponta Grossa"),
    ("Universidade Estadual do Centro-Oeste (UNICENTRO)", "PR", "Guarapuava"),
    ("Universidade Estadual do Norte do Parana (UENP)", "PR", "Jacarezinho"),
    ("Universidade Estadual do Oeste do Parana (UNIOESTE)", "PR", "Cascavel"),
    ("Universidade Estadual do Parana (UNESPAR)", "PR", "Curitiba"),
    ("Universidade Estadual do Rio Grande do Sul (UERGS)", "RS", "Porto Alegre"),
    ("Universidade do Estado de Santa Catarina (UDESC)", "SC", "Florianopolis"),
    ("Universidade Estadual de Goias (UEG)", "GO", "Anapolis"),
    ("Universidade do Estado de Mato Grosso (UNEMAT)", "MT", "Caceres"),
    ("Universidade Estadual de Mato Grosso do Sul (UEMS)", "MS", "Dourados"),
    ("Universidade Estadual do Maranhao (UEMA)", "MA", "Sao Luis"),
    ("Universidade do Estado do Para (UEPA)", "PA", "Belem"),
    ("Universidade do Estado do Amazonas (UEA)", "AM", "Manaus"),
    ("Universidade Estadual do Piaui (UESPI)", "PI", "Teresina"),
    ("Universidade do Estado do Rio Grande do Norte (UERN)", "RN", "Mossoro"),
    ("Universidade Estadual da Paraiba (UEPB)", "PB", "Campina Grande"),
    ("Universidade Estadual de Alagoas (UNEAL)", "AL", "Arapiraca"),
    ("Universidade Estadual do Tocantins (UNITINS)", "TO", "Palmas"),
    ("Pontificia Universidade Catolica de Sao Paulo (PUC-SP)", "SP", "Sao Paulo"),
    ("Pontificia Universidade Catolica do Rio de Janeiro (PUC-Rio)", "RJ", "Rio de Janeiro"),
    ("Pontificia Universidade Catolica de Minas Gerais (PUC Minas)", "MG", "Belo Horizonte"),
    ("Pontificia Universidade Catolica do Rio Grande do Sul (PUCRS)", "RS", "Porto Alegre"),
    ("Pontificia Universidade Catolica do Parana (PUCPR)", "PR", "Curitiba"),
    ("Pontificia Universidade Catolica de Campinas (PUC-Campinas)", "SP", "Campinas"),
    ("Universidade Presbiteriana Mackenzie", "SP", "Sao Paulo"),
    ("Universidade do Vale do Rio dos Sinos (UNISINOS)", "RS", "Sao Leopoldo"),
    ("Universidade de Caxias do Sul (UCS)", "RS", "Caxias do Sul"),
    ("Universidade Regional de Blumenau (FURB)", "SC", "Blumenau"),
    ("Universidade do Vale do Itajai (UNIVALI)", "SC", "Itajai"),
    ("Universidade do Oeste de Santa Catarina (UNOESC)", "SC", "Joacaba"),
    ("Universidade do Sul de Santa Catarina (UNISUL)", "SC", "Tubarao"),
    ("Universidade Norte do Parana (UNOPAR)", "PR", "Londrina"),
    ("Universidade Positivo (UP)", "PR", "Curitiba"),
    ("Universidade do Vale do Paraiba (UNIVAP)", "SP", "Sao Jose dos Campos"),
    ("Universidade de Ribeirao Preto (UNAERP)", "SP", "Ribeirao Preto"),
    ("Universidade Sao Judas Tadeu (USJT)", "SP", "Sao Paulo"),
    # Federais
    ("Universidade Federal de Sao Paulo (UNIFESP)", "SP", "Sao Paulo"),
    ("Universidade Federal do ABC (UFABC)", "SP", "Santo Andre"),
    ("Universidade Federal do Rio de Janeiro (UFRJ)", "RJ", "Rio de Janeiro"),
    ("Universidade Federal Fluminense (UFF)", "RJ", "Niteroi"),
    ("Universidade Federal Rural do Rio de Janeiro (UFRRJ)", "RJ", "Seropedica"),
    ("Universidade Federal de Minas Gerais (UFMG)", "MG", "Belo Horizonte"),
    ("Universidade Federal de Itajuba (UNIFEI)", "MG", "Itajuba"),
    ("Universidade Federal de Uberlandia (UFU)", "MG", "Uberlandia"),
    ("Universidade Federal de Juiz de Fora (UFJF)", "MG", "Juiz de Fora"),
    ("Universidade Federal do Parana (UFPR)", "PR", "Curitiba"),
    ("Universidade Tecnologica Federal do Parana (UTFPR)", "PR", "Curitiba"),
    ("Universidade Federal do Rio Grande do Sul (UFRGS)", "RS", "Porto Alegre"),
    ("Universidade Federal de Santa Maria (UFSM)", "RS", "Santa Maria"),
    ("Universidade Federal de Pelotas (UFPel)", "RS", "Pelotas"),
    ("Universidade Federal de Santa Catarina (UFSC)", "SC", "Florianopolis"),
    ("Universidade Federal de Bahia (UFBA)", "BA", "Salvador"),
    ("Universidade Federal de Feira de Santana (UEFS Fed)", "BA", "Feira de Santana"),
    ("Universidade Federal do Ceara (UFC)", "CE", "Fortaleza"),
    ("Universidade Federal do Rio Grande do Norte (UFRN)", "RN", "Natal"),
    ("Universidade Federal da Paraiba (UFPB)", "PB", "Joao Pessoa"),
    ("Universidade Federal de Pernambuco (UFPE)", "PE", "Recife"),
    ("Universidade Federal de Alagoas (UFAL)", "AL", "Maceio"),
    ("Universidade Federal de Sergipe (UFS)", "SE", "Aracaju"),
    ("Universidade Federal do Maranhao (UFMA)", "MA", "Sao Luis"),
    ("Universidade Federal do Piaui (UFPI)", "PI", "Teresina"),
    ("Universidade Federal do Para (UFPA)", "PA", "Belem"),
    ("Universidade Federal do Amazonas (UFAM)", "AM", "Manaus"),
    ("Universidade Federal de Goias (UFG)", "GO", "Goiania"),
    ("Universidade Federal de Mato Grosso (UFMT)", "MT", "Cuiaba"),
    ("Universidade Federal de Mato Grosso do Sul (UFMS)", "MS", "Campo Grande"),
    ("Universidade Federal do Espirito Santo (UFES)", "ES", "Vitoria"),
    ("Universidade de Brasilia (UnB)", "DF", "Brasilia"),
    ("Universidade Federal do Tocantins (UFT)", "TO", "Palmas"),
    ("Universidade Federal de Rondonia (UNIR)", "RO", "Porto Velho"),
    ("Universidade Federal de Roraima (UFRR)", "RR", "Boa Vista"),
    ("Universidade Federal do Amapa (UNIFAP)", "AP", "Macapa"),
    ("Universidade Federal do Acre (UFAC)", "AC", "Rio Branco"),
]


def seed_db(db):
    """Insere todas as instituicoes se o banco estiver vazio."""
    if db.query(Institution).count() > 0:
        return

    print("[SEED] Banco vazio — inserindo instituicoes...")
    items = (
        [(n, "school",     s, c) for n, s, c in ESCOLAS] +
        [(n, "city",       s, c) for n, s, c in CIDADES] +
        [(n, "company",    s, c) for n, s, c in EMPRESAS] +
        [(n, "university", s, c) for n, s, c in UNIVERSIDADES]
    )
    db.add_all([
        Institution(name=n, type=t, state=s, city=c, approved=True)
        for n, t, s, c in items
    ])
    db.commit()
    print(f"[SEED] {len(items)} instituicoes inseridas.")
