-- Migration 005: Túnel do Tempo Foundation
--
-- Adds:
--   * tunel_uploads  Old-photo uploads (LGPD-sensitive: holds personal images).
--                    Soft-delete via deleted_at; cron purges rows + files >30d.
--   * tunel_faces    Per-face records w/ bbox, embedding (biometric → LGPD-sensitive),
--                    optional match to a registered user (matched_user_id).
--
-- LGPD notes:
--   - embedding column is BIOMETRIC DATA → never expose via public APIs, never log.
--   - deleted_at enables soft-delete; a 30-day purge job must hard-delete the row
--     AND remove the file at file_path from disk.
--   - exif_scrubbed flag tracks whether upload pipeline stripped GPS/camera metadata.
--
-- Cross-dialect: written for Postgres (Neon, prod). SQLAlchemy create_all handles
-- SQLite fallback via the ORM models in database.py (TunelUpload, TunelFace).
-- All statements use IF NOT EXISTS for idempotency.

-- ────────────────────────────────────────────────────────────────────────
-- 1. tunel_uploads — one row per uploaded old photo
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tunel_uploads (
    id                    SERIAL PRIMARY KEY,
    user_id               INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    turma_id              INTEGER REFERENCES turmas(id) ON DELETE SET NULL,
    file_path             VARCHAR(500) NOT NULL,
    file_size_bytes       INTEGER NOT NULL,
    mime_type             VARCHAR(50) NOT NULL,
    original_filename     VARCHAR(255),
    photo_year_estimated  INTEGER,
    photo_context         VARCHAR(200),
    faces_detected_count  INTEGER DEFAULT 0,
    processing_status     VARCHAR(20) DEFAULT 'pending',
    exif_scrubbed         BOOLEAN DEFAULT FALSE,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at            TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_tunel_uploads_user_id
    ON tunel_uploads (user_id);

CREATE INDEX IF NOT EXISTS ix_tunel_uploads_turma_id
    ON tunel_uploads (turma_id);

CREATE INDEX IF NOT EXISTS ix_tunel_uploads_processing_status
    ON tunel_uploads (processing_status);

CREATE INDEX IF NOT EXISTS ix_tunel_uploads_deleted_at
    ON tunel_uploads (deleted_at);

-- ────────────────────────────────────────────────────────────────────────
-- 2. tunel_faces — one row per face detected within an upload
-- ────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tunel_faces (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id         INTEGER NOT NULL REFERENCES tunel_uploads(id) ON DELETE CASCADE,
    face_index        INTEGER NOT NULL,
    bbox_x            INTEGER,
    bbox_y            INTEGER,
    bbox_w            INTEGER,
    bbox_h            INTEGER,
    embedding         JSON,
    embedding_model   VARCHAR(50),
    confidence        DOUBLE PRECISION,
    matched_user_id   INTEGER REFERENCES users(id) ON DELETE SET NULL,
    match_confidence  DOUBLE PRECISION,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_tunel_faces_upload_id
    ON tunel_faces (upload_id);

CREATE INDEX IF NOT EXISTS ix_tunel_faces_matched_user_id
    ON tunel_faces (matched_user_id);

-- ────────────────────────────────────────────────────────────────────────
-- 3. LGPD reminders (comments only, no DDL)
-- ────────────────────────────────────────────────────────────────────────
COMMENT ON TABLE tunel_uploads IS 'Túnel do Tempo old-photo uploads. LGPD: soft-delete via deleted_at; 30-day cron purge required.';
COMMENT ON TABLE tunel_faces IS 'Detected faces with biometric embeddings. LGPD-sensitive: never expose embedding via public APIs.';
COMMENT ON COLUMN tunel_faces.embedding IS 'Biometric vector (128 or 512 dims). LGPD: sensitive data — never log, never expose.';
COMMENT ON COLUMN tunel_uploads.deleted_at IS 'Soft-delete timestamp. Hard delete (row + file) must occur after 30 days.';
